apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where redis and all its infrastructure will be installed.
namespace: redis

configMapGenerator:
- name: redis-pwd-config
  files:
  - redis.conf
resources:
- redis-pod.yml
